version: '3'
services:
  app:
    volumes:
    - ./LocalSettings.php:/var/www/html/LocalSettings.php
  mysql:
    image: mysql:5.7
    volumes:
    - mysql_data:/var/lib/mysql
    ports:
    - "${MYSQL_PORT:-3306}:3306"
    env_file:
    - .env
volumes:
  mysql_data: